# Generated by Django 4.0 on 2021-12-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='body',
            field=models.TextField(default='', max_length=400, verbose_name='詳細/内容'),
        ),
    ]
